package chatmodule;


/**
* chatmodule/ClientsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public final class ClientsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ClientsHolder ()
  {
  }

  public ClientsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.ClientsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.ClientsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.ClientsHelper.type ();
  }

}
