package chatmodule;

/**
* chatmodule/ConnectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public final class ConnectionHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Connection value = null;

  public ConnectionHolder ()
  {
  }

  public ConnectionHolder (chatmodule.Connection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.ConnectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.ConnectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.ConnectionHelper.type ();
  }

}
