package chatmodule;


/**
* chatmodule/ConnectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public interface ConnectionOperations 
{
  String[] clients ();
  void clients (String[] newClients);
  chatmodule.Receiver[] recivers ();
  void recivers (chatmodule.Receiver[] newRecivers);
  chatmodule.Emitter[] emitter ();
  void emitter (chatmodule.Emitter[] newEmitter);
  chatmodule.Emitter connect (String nickname, chatmodule.Receiver rcv);
  void disconnect (String nickname);
} // interface ConnectionOperations
