package chatmodule;


/**
* chatmodule/Connection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public interface Connection extends ConnectionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Connection
