package chatmodule;

/**
* chatmodule/EmitterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public final class EmitterHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Emitter value = null;

  public EmitterHolder ()
  {
  }

  public EmitterHolder (chatmodule.Emitter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.EmitterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.EmitterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.EmitterHelper.type ();
  }

}
