package chatmodule;


/**
* chatmodule/EmitterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public abstract class EmitterPOA extends org.omg.PortableServer.Servant
 implements chatmodule.EmitterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_client", new java.lang.Integer (0));
    _methods.put ("_set_client", new java.lang.Integer (1));
    _methods.put ("sendMassage", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chatmodule/Emitter/_get_client
       {
         String $result = null;
         $result = this.client ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // chatmodule/Emitter/_set_client
       {
         String newClient = in.read_string ();
         this.client (newClient);
         out = $rh.createReply();
         break;
       }

       case 2:  // chatmodule/Emitter/sendMassage
       {
         String to = in.read_string ();
         String message = in.read_string ();
         this.sendMassage (to, message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chatmodule/Emitter:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Emitter _this() 
  {
    return EmitterHelper.narrow(
    super._this_object());
  }

  public Emitter _this(org.omg.CORBA.ORB orb) 
  {
    return EmitterHelper.narrow(
    super._this_object(orb));
  }


} // class EmitterPOA
