package chatmodule;


/**
* chatmodule/LesEmmeteursHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public final class LesEmmeteursHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Emitter value[] = null;

  public LesEmmeteursHolder ()
  {
  }

  public LesEmmeteursHolder (chatmodule.Emitter[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.LesEmmeteursHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.LesEmmeteursHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.LesEmmeteursHelper.type ();
  }

}
