package chatmodule;


/**
* chatmodule/LesRecepteursHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public final class LesRecepteursHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Receiver value[] = null;

  public LesRecepteursHolder ()
  {
  }

  public LesRecepteursHolder (chatmodule.Receiver[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.LesRecepteursHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.LesRecepteursHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.LesRecepteursHelper.type ();
  }

}
