package chatmodule;


/**
* chatmodule/ReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public interface ReceiverOperations 
{
  String message ();
  void message (String newMessage);
  String client ();
  void client (String newClient);
  void receive (String from, String message);
  void initClients (String[] clients);
  void addClient (String client);
  void remClient (String client);
} // interface ReceiverOperations
