package chatmodule;

/**
* chatmodule/ReceiverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 22 h 12 CET
*/

public final class ReceiverHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Receiver value = null;

  public ReceiverHolder ()
  {
  }

  public ReceiverHolder (chatmodule.Receiver initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.ReceiverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.ReceiverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.ReceiverHelper.type ();
  }

}
